# user variables, change this to make custom site.

name: Lemma
desc: Yet another simple theme for Jekyll.
author:
  name: neizod
  avatar: //gravatar.com/avatar/daa1cc36ed2ab0d13045d5cd2431cde9?s=320
  profile: |
    Just another ordinary grad student in computer engineering.
    I'm interest in programming language, algorithm, and mathematics.

    I live in Chiang Mai or Bangkok, Thailand.
    And you may found me around BarCamp event ;D
  socials:
    facebook:
    twitter: //twitter.com/neizod
    google-plus:
    github: //github.com/neizod
    stack-overflow: //stackoverflow.com/users/889578/neizod
    instagram:
    pinterest:
    steam: //steamcommunity.com/id/neizod/
license: MIT License


# theme variables, change this to make site looks best.
baseurl: /lemma-theme
paginate: 2


# system variables, do not change unless you knew what's it does.
paginate_path: page/:num
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
